name: chat_bot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dash_chat_2: ^0.0.21
  chat_gpt_sdk: ^3.1.5
  http: ^1.5.0
  fl_chart: ^0.63.0
  shared_preferences: ^2.5.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bot_avatar.png
    - assets/images/bot2_avatar.png
    - assets/images/questions.json
